---

- name: Install Amazon-Linux-2023-specific support packages
  ansible.builtin.dnf:
    name:
      - dejavu-sans-fonts
      - file
      - git
      - libxml2
      - shadow-utils

- name: Uninstall curl-minimal (conflicts with curl)
  ansible.builtin.dnf:
    name: curl-minimal
    state: absent
    autoremove: no
